runtime: python27
api_version: 1
# threadsafe: true
threadsafe: false

handlers:
- url: /static
  static_dir: static
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
